"""init schema

Revision ID: 981910489793
Revises: 
Create Date: 2026-02-06 15:14:16.193057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '981910489793'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_otps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=True),
    sa.Column('code_hash', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_otps_email'), 'email_otps', ['email'], unique=False)
    op.create_index('ix_email_otps_email_expires', 'email_otps', ['email', 'expires_at'], unique=False)
    op.create_index(op.f('ix_email_otps_ip'), 'email_otps', ['ip'], unique=False)
    op.create_index('ix_email_otps_ip_created', 'email_otps', ['ip', 'created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wechat_login_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wechat_login_states_state'), 'wechat_login_states', ['state'], unique=True)
    op.create_table('bullets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_root', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['bullets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'is_root', name='uq_user_root')
    )
    op.create_index(op.f('ix_bullets_parent_id'), 'bullets', ['parent_id'], unique=False)
    op.create_index(op.f('ix_bullets_user_id'), 'bullets', ['user_id'], unique=False)
    op.create_index('ix_bullets_user_parent_order', 'bullets', ['user_id', 'parent_id', 'order_index'], unique=False)
    op.create_index('ix_bullets_user_root', 'bullets', ['user_id', 'is_root'], unique=False)
    op.create_table('identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=36), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_provider_subject')
    )
    op.create_index('ix_identities_provider_subject', 'identities', ['provider', 'provider_subject'], unique=False)
    op.create_index(op.f('ix_identities_user_id'), 'identities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identities_user_id'), table_name='identities')
    op.drop_index('ix_identities_provider_subject', table_name='identities')
    op.drop_table('identities')
    op.drop_index('ix_bullets_user_root', table_name='bullets')
    op.drop_index('ix_bullets_user_parent_order', table_name='bullets')
    op.drop_index(op.f('ix_bullets_user_id'), table_name='bullets')
    op.drop_index(op.f('ix_bullets_parent_id'), table_name='bullets')
    op.drop_table('bullets')
    op.drop_index(op.f('ix_wechat_login_states_state'), table_name='wechat_login_states')
    op.drop_table('wechat_login_states')
    op.drop_table('users')
    op.drop_index('ix_email_otps_ip_created', table_name='email_otps')
    op.drop_index(op.f('ix_email_otps_ip'), table_name='email_otps')
    op.drop_index('ix_email_otps_email_expires', table_name='email_otps')
    op.drop_index(op.f('ix_email_otps_email'), table_name='email_otps')
    op.drop_table('email_otps')
    # ### end Alembic commands ###
